add WriteHandle::take
jonhoo/left-right pull request #96
Opened 2021-05-04 11:19 UTC by pYtoner

There might be a less clear way to let the Drop know that it needs to do things differently but a bool is not much overhead.

I am not sure how the usage of drop second should be documented. But what I wrote should be a good start I think.

2021-05-04 11:28 UTC, pYtoner commented on src/write.rs
> +            return;
There is a test coverage warning that says this wasn't covered by tests. But it gets called when the take functions returns.

2021-05-04 11:35 UTC, pYtoner commented
Should the version of the crate be changed also?

2021-05-05 02:25 UTC, jonhoo requested changes
Ah, no, no need to update the version number -- I'll take care of that.

I'd like to see this take a slightly different approach that lets us share the code between `drop` and `take`. Specifically, what I'm thinking is to add a `take_inner(&mut self) -> Option<T>` that does all the stuff `take`/`drop` currently does. Then, call that from both `drop` and `take`, with `drop` just dropping the return value. Does that make sense? This code is hairy enough that I don't want it repeated if we can avoid it.

2021-05-05 10:46 UTC, pYtoner commented
That seems like a good approach. I'll do it today.

2021-05-05 11:50 UTC, closed without merging

2021-05-06 01:55 UTC, jonhoo commented
Oh, by the way, you don't need to open a new PR for each change. You can just push another commit to the branch you made the commit from :)

2021-05-06 10:43 UTC, pYtoner commented
Oh that makes it much easier. Thanks for letting me know. My first time contributing so things are new and fun :)